# strongly agree = -3, moderately agree = -2, agree = -1, not sure = 0, disagee = 1, moderately disagree = 2, strongly disagree = 3
PAY_LOAD_EN = {
    "questions": [
        {"text": "You regularly make new friends.", "answer": None},
        {
            "text": "You spend a lot of your free time exploring various random topics that pique your interest.",
            "answer": None,
        },
        {
            "text": "Seeing other people cry can easily make you feel like you want to cry too.",
            "answer": None,
        },
        {"text": "You often make a backup plan for a backup plan.", "answer": None},
        {
            "text": "You usually stay calm, even under a lot of pressure.",
            "answer": None,
        },
        {
            "text": "At social events, you rarely try to introduce yourself to new people and mostly talk to the ones you already know.",
            "answer": None,
        },
        {
            "text": "You prefer to completely finish one project before starting another.",
            "answer": None,
        },
        {"text": "You are very sentimental.", "answer": None},
        {
            "text": "You like to use organizing tools like schedules and lists.",
            "answer": None,
        },
        {
            "text": "Even a small mistake can cause you to doubt your overall abilities and knowledge.",
            "answer": None,
        },
        {
            "text": "You feel comfortable just walking up to someone you find interesting and striking up a conversation.",
            "answer": None,
        },
        {
            "text": "You are not too interested in discussing various interpretations and analyses of creative works.",
            "answer": None,
        },
        {
            "text": "You are more inclined to follow your head than your heart.",
            "answer": None,
        },
        {
            "text": "You usually prefer just doing what you feel like at any given moment instead of planning a particular daily routine.",
            "answer": None,
        },
        {
            "text": "You rarely worry about whether you make a good impression on people you meet.",
            "answer": None,
        },
        {"text": "You enjoy participating in group activities.", "answer": None},
        {
            "text": "You like books and movies that make you come up with your own interpretation of the ending.",
            "answer": None,
        },
        {
            "text": "Your happiness comes more from helping others accomplish things than your own accomplishments.",
            "answer": None,
        },
        {
            "text": "You are interested in so many things that you find it difficult to choose what to try next.",
            "answer": None,
        },
        {
            "text": "You are prone to worrying that things will take a turn for the worse.",
            "answer": None,
        },
        {"text": "You avoid leadership roles in group settings.", "answer": None},
        {"text": "You are definitely not an artistic type of person.", "answer": None},
        {
            "text": "You think the world would be a better place if people relied more on rationality and less on their feelings.",
            "answer": None,
        },
        {
            "text": "You prefer to do your chores before allowing yourself to relax.",
            "answer": None,
        },
        {"text": "You enjoy watching people argue.", "answer": None},
        {"text": "You tend to avoid drawing attention to yourself.", "answer": None},
        {"text": "Your mood can change very quickly.", "answer": None},
        {
            "text": "You lose patience with people who are not as efficient as you.",
            "answer": None,
        },
        {
            "text": "You often end up doing things at the last possible moment.",
            "answer": None,
        },
        {
            "text": "You have always been fascinated by the question of what, if anything, happens after death.",
            "answer": None,
        },
        {
            "text": "You usually prefer to be around others rather than on your own.",
            "answer": None,
        },
        {
            "text": "You become bored or lose interest when the discussion gets highly theoretical.",
            "answer": None,
        },
        {
            "text": "You find it easy to empathize with a person whose experiences are very different from yours.",
            "answer": None,
        },
        {
            "text": "You usually postpone finalizing decisions for as long as possible.",
            "answer": None,
        },
        {
            "text": "You rarely second-guess the choices that you have made.",
            "answer": None,
        },
        {
            "text": "After a long and exhausting week, a lively social event is just what you need.",
            "answer": None,
        },
        {"text": "You enjoy going to art museums.", "answer": None},
        {
            "text": "You often have a hard time understanding other people’s feelings.",
            "answer": None,
        },
        {"text": "You like to have a to-do list for each day.", "answer": None},
        {"text": "You rarely feel insecure.", "answer": None},
        {"text": "You avoid making phone calls.", "answer": None},
        {
            "text": "You often spend a lot of time trying to understand views that are very different from your own.",
            "answer": None,
        },
        {
            "text": "In your social circle, you are often the one who contacts your friends and initiates activities.",
            "answer": None,
        },
        {
            "text": "If your plans are interrupted, your top priority is to get back on track as soon as possible.",
            "answer": None,
        },
        {
            "text": "You are still bothered by mistakes that you made a long time ago.",
            "answer": None,
        },
        {
            "text": "You rarely contemplate the reasons for human existence or the meaning of life.",
            "answer": None,
        },
        {
            "text": "Your emotions control you more than you control them.",
            "answer": None,
        },
        {
            "text": "You take great care not to make people look bad, even when it is completely their fault.",
            "answer": None,
        },
        {
            "text": "Your personal work style is closer to spontaneous bursts of energy than organized and consistent efforts.",
            "answer": None,
        },
        {
            "text": "When someone thinks highly of you, you wonder how long it will take them to feel disappointed in you.",
            "answer": None,
        },
        {
            "text": "You would love a job that requires you to work alone most of the time.",
            "answer": None,
        },
        {
            "text": "You believe that pondering abstract philosophical questions is a waste of time.",
            "answer": None,
        },
        {
            "text": "You feel more drawn to places with busy, bustling atmospheres than quiet, intimate places.",
            "answer": None,
        },
        {"text": "You know at first glance how someone is feeling.", "answer": None},
        {"text": "You often feel overwhelmed.", "answer": None},
        {
            "text": "You complete things methodically without skipping over any steps.",
            "answer": None,
        },
        {
            "text": "You are very intrigued by things labeled as controversial.",
            "answer": None,
        },
        {
            "text": "You would pass along a good opportunity if you thought someone else needed it more.",
            "answer": None,
        },
        {"text": "You struggle with deadlines.", "answer": None},
        {
            "text": "You feel confident that things will work out for you.",
            "answer": None,
        },
    ],
    "gender": None,
    "inviteCode": "",
    "teamInviteKey": "",
    "extraData": [],
}

PAY_LOAD_CN = {
    "questions": [
        {"text": "你经常交新朋友。", "answer": None},
        {"text": "你会花很多空闲时间探索各种激起您兴趣的随机主题。", "answer": None},
        {"text": "看到别人哭，很容易让你也觉得想哭。", "answer": None},
        {"text": "你经常为备用计划再制定一个备用计划。", "answer": None},
        {"text": "你通常会保持冷静，即使在很大的压力下。", "answer": None},
        {
            "text": "在社交活动中，你很少主动去认识新的人，大多数时间都是和已经认识的人交谈。",
            "answer": None,
        },
        {"text": "你喜欢在完全完成一个项目后，再开始另一个项目。", "answer": None},
        {"text": "你非常感性。", "answer": None},
        {"text": "你喜欢使用日程表和清单等组织工具。", "answer": None},
        {
            "text": "即使是一个小错误也会让你怀疑自己的整体能力和知识水平。",
            "answer": None,
        },
        {
            "text": "走到你觉得有趣的人身边，然后开始一段谈话，这会让你感觉很舒服。",
            "answer": None,
        },
        {"text": "你对讨论创意作品的各种解读和分析不太感兴趣。", "answer": None},
        {"text": "你更喜欢用理智做决定，而非情感。", "answer": None},
        {
            "text": "你做事通常更喜欢随心所欲，而不是按照特定的日常计划。",
            "answer": None,
        },
        {"text": "你很少担心你是否给人留下好印象。", "answer": None},
        {"text": "你喜欢参加集体活动。", "answer": None},
        {"text": "你喜欢让你自己解读结局的书籍和电影。", "answer": None},
        {"text": "与自我成就相比，帮助他人实现目标会让你感觉更快乐。", "answer": None},
        {"text": "你对很多事情感兴趣，因此很难选择下一步尝试什么。", "answer": None},
        {"text": "你往往会担心事情会朝着更糟糕的方向发展。", "answer": None},
        {"text": "你避免在小组环境中扮演领导角色。", "answer": None},
        {"text": "你绝对不是艺术型的人。", "answer": None},
        {
            "text": "你认为如果人们更依赖理性，而不是过于依赖自己的感受，世界会变得更好。",
            "answer": None,
        },
        {"text": "你更喜欢先做家务，然后再放松。", "answer": None},
        {"text": "你喜欢看人争吵。", "answer": None},
        {"text": "你尽量避免吸引别人的注意力。", "answer": None},
        {"text": "你的心情会迅速变化。", "answer": None},
        {"text": "你对效率不如你的人没有耐心。", "answer": None},
        {"text": "你常常在最后一刻才开始行动。", "answer": None},
        {"text": "你总是对死后会发生什么事情感到好奇。", "answer": None},
        {"text": "你通常更喜欢和别人在一起，而不是独自一人。", "answer": None},
        {"text": "当讨论变得高度理论化时，你会觉得无聊或失去兴趣。", "answer": None},
        {"text": "你发现自己很容易理解经历与自己截然不同的人。", "answer": None},
        {"text": "你通常会尽可能推迟最终决定。", "answer": None},
        {"text": "你很少对自己做出的选择产生怀疑。", "answer": None},
        {
            "text": "经过漫长而疲惫的一周，一场热闹的社交活动正是你所需要的。",
            "answer": None,
        },
        {"text": "你喜欢参观艺术博物馆。", "answer": None},
        {"text": "你经常很难理解别人的感受。", "answer": None},
        {"text": "你喜欢每天都有一份待办事项清单", "answer": None},
        {"text": "你很少会感觉没有安全感。", "answer": None},
        {"text": "你会避免打电话。", "answer": None},
        {"text": "你经常花很多时间试图理解与你自己截然不同的观点。", "answer": None},
        {"text": "在你的社交圈里，你经常是联系朋友并发起活动的人。", "answer": None},
        {"text": "如果你的计划被打断，你的首要任务是尽快回到正轨。", "answer": None},
        {"text": "你仍然被你很久以前犯的错误所困扰。", "answer": None},
        {"text": "你很少考虑人类存在的原因或生命的意义。", "answer": None},
        {"text": "你对情绪的控制力不如情绪对你的控制力。", "answer": None},
        {"text": "你尽量不让别人难堪，即使这完全是他们的错。", "answer": None},
        {
            "text": "你的个人工作方式更偏向于自发的能量爆发，而不是有条理的持续努力。",
            "answer": None,
        },
        {
            "text": "当有人对你评价很高时，你会想知道他们需要多长时间就会对你失望。",
            "answer": None,
        },
        {"text": "你喜欢大部分时间都需要你独自完成的工作。", "answer": None},
        {"text": "你认为思考抽象的哲学问题是浪费时间。", "answer": None},
        {"text": "与安静、私密的地方相比，你更喜欢繁忙、热闹的地方。", "answer": None},
        {"text": "你一眼就能知道别人的感受。", "answer": None},
        {"text": "你经常感到难以承受。", "answer": None},
        {"text": "你按部就班地完成事情，不遗漏任何步骤。", "answer": None},
        {"text": "你对有争议的事物非常感兴趣。", "answer": None},
        {"text": "如果你认为别人更需要它，你会把一个好机会让出去。", "answer": None},
        {"text": "你很难在最后期限前完成任务。", "answer": None},
        {"text": "你相信事情会朝对自己有利的方向发展。", "answer": None},
    ],
    "gender": None,
    "inviteCode": "",
    "teamInviteKey": "",
    "extraData": [],
}

TEST_PAYLOAD = {
    "questions": [
        {"text": "你经常交新朋友。", "answer": 1},
        {"text": "你会花很多空闲时间探索各种激起您兴趣的随机主题。", "answer": -3},
        {"text": "看到别人哭，很容易让你也觉得想哭。", "answer": -1},
        {"text": "你经常为备用计划再制定一个备用计划。", "answer": 0},
        {"text": "你通常会保持冷静，即使在很大的压力下。", "answer": -2},
        {
            "text": "在社交活动中，你很少主动去认识新的人，大多数时间都是和已经认识的人交谈。",
            "answer": -2,
        },
        {"text": "你喜欢在完全完成一个项目后，再开始另一个项目。", "answer": -2},
        {"text": "你非常感性。", "answer": -2},
        {"text": "你喜欢使用日程表和清单等组织工具。", "answer": -1},
        {
            "text": "即使是一个小错误也会让你怀疑自己的整体能力和知识水平。",
            "answer": -2,
        },
        {
            "text": "走到你觉得有趣的人身边，然后开始一段谈话，这会让你感觉很舒服。",
            "answer": -3,
        },
        {"text": "你对讨论创意作品的各种解读和分析不太感兴趣。", "answer": 0},
        {"text": "你更喜欢用理智做决定，而非情感。", "answer": -3},
        {
            "text": "你做事通常更喜欢随心所欲，而不是按照特定的日常计划。",
            "answer": 1,
        },
        {"text": "你很少担心你是否给人留下好印象。", "answer": 2},
        {"text": "你喜欢参加集体活动。", "answer": 2},
        {"text": "你喜欢让你自己解读结局的书籍和电影。", "answer": 2},
        {"text": "与自我成就相比，帮助他人实现目标会让你感觉更快乐。", "answer": -2},
        {"text": "你对很多事情感兴趣，因此很难选择下一步尝试什么。", "answer": 0},
        {"text": "你往往会担心事情会朝着更糟糕的方向发展。", "answer": -3},
        {"text": "你避免在小组环境中扮演领导角色。", "answer": -2},
        {"text": "你绝对不是艺术型的人。", "answer": -3},
        {
            "text": "你认为如果人们更依赖理性，而不是过于依赖自己的感受，世界会变得更好。",
            "answer": -1,
        },
        {"text": "你更喜欢先做家务，然后再放松。", "answer": -2},
        {"text": "你喜欢看人争吵。", "answer": -1},
        {"text": "你尽量避免吸引别人的注意力。", "answer": -3},
        {"text": "你的心情会迅速变化。", "answer": 0},
        {"text": "你对效率不如你的人没有耐心。", "answer": -2},
        {"text": "你常常在最后一刻才开始行动。", "answer": 2},
        {"text": "你总是对死后会发生什么事情感到好奇。", "answer": -3},
        {"text": "你通常更喜欢和别人在一起，而不是独自一人。", "answer": 2},
        {"text": "当讨论变得高度理论化时，你会觉得无聊或失去兴趣。", "answer": 2},
        {"text": "你发现自己很容易理解经历与自己截然不同的人。", "answer": -2},
        {"text": "你通常会尽可能推迟最终决定。", "answer": -1},
        {"text": "你很少对自己做出的选择产生怀疑。", "answer": 1},
        {
            "text": "经过漫长而疲惫的一周，一场热闹的社交活动正是你所需要的。",
            "answer": 3,
        },
        {"text": "你喜欢参观艺术博物馆。", "answer": 3},
        {"text": "你经常很难理解别人的感受。", "answer": 2},
        {"text": "你喜欢每天都有一份待办事项清单", "answer": -2},
        {"text": "你很少会感觉没有安全感。", "answer": -2},
        {"text": "你会避免打电话。", "answer": -3},
        {"text": "你经常花很多时间试图理解与你自己截然不同的观点。", "answer": -1},
        {"text": "在你的社交圈里，你经常是联系朋友并发起活动的人。", "answer": 3},
        {"text": "如果你的计划被打断，你的首要任务是尽快回到正轨。", "answer": -2},
        {"text": "你仍然被你很久以前犯的错误所困扰。", "answer": -2},
        {"text": "你很少考虑人类存在的原因或生命的意义。", "answer": 3},
        {"text": "你对情绪的控制力不如情绪对你的控制力。", "answer": 3},
        {"text": "你尽量不让别人难堪，即使这完全是他们的错。", "answer": -3},
        {
            "text": "你的个人工作方式更偏向于自发的能量爆发，而不是有条理的持续努力。",
            "answer": 0,
        },
        {
            "text": "当有人对你评价很高时，你会想知道他们需要多长时间就会对你失望。",
            "answer": -1,
        },
        {"text": "你喜欢大部分时间都需要你独自完成的工作。", "answer": -3},
        {"text": "你认为思考抽象的哲学问题是浪费时间。", "answer": 3},
        {"text": "与安静、私密的地方相比，你更喜欢繁忙、热闹的地方。", "answer": 0},
        {"text": "你一眼就能知道别人的感受。", "answer": -1},
        {"text": "你经常感到难以承受。", "answer": 1},
        {"text": "你按部就班地完成事情，不遗漏任何步骤。", "answer": -2},
        {"text": "你对有争议的事物非常感兴趣。", "answer": -2},
        {"text": "如果你认为别人更需要它，你会把一个好机会让出去。", "answer": 1},
        {"text": "你很难在最后期限前完成任务。", "answer": 3},
        {"text": "你相信事情会朝对自己有利的方向发展。", "answer": -2},
    ],
    "gender": None,
    "inviteCode": "",
    "teamInviteKey": "",
    "extraData": [],
}
